// This file is autogenerated. Do not hand edit.

KernelTun(3.0.0.1/8) -> Discard;
KernelTun(4.0.0.1/8) -> Discard;
KernelTun(1.0.0.1/8) -> Discard;
KernelTun(2.0.0.1/8) -> Discard;
KernelTun(5.0.0.1/8) -> Discard;
